<?php

/**
 * @file
 * Forces users to register if they want to continue using the website
 *
 * Squeeze configuration settings allow a site administrator to enable squeeze
 * functionality for entire site or for individual nodes.  
 * The default behavior is that squeeze functionality is off. Enabling is done
 * via the admin->configuration->squeeze settings page. 
 * Once squeeze functionality is enabled, you can choose the squeeze type:
 * a.) a timer
 * b.) clicks
 */

/**
 * Implements hook_menu();
 * 
 * Create squeeze configuration page for admins 
 */
function squeeze_menu() {
  $items['admin/config/squeeze'] = array(
    'title' => 'Squeeze',
    'description' => 'Manage squeeze settings.',
    'position' => 'right',
    'weight' => -99,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  
  $items['admin/config/squeeze/settings'] = array(
    'title' => 'Squeeze settings',
    'description' => 'Enable squeeze pages and choose how they behave.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('squeeze_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'squeeze.admin.inc',
  );
  
  return $items;
}



/**
 * Implements hook_init();
 */
function squeeze_init() {  
  //if timer enabled
  //add javascript timer
  //grab variable and put into the javascript function
  $enable = variable_get('squeeze_enable');
  if($enable == "1") {
    $time = variable_get('squeeze_timer');
    $timeInMilliseconds = $time * 1000;
    drupal_add_js("jQuery(document).ready(function() { 
      setTimeout(function(){
        jQuery('#name-and-slogan').css({'background-color':'green'});
      }, $timeInMilliseconds);
    });", 'inline');
    
  }
  
  //if clicks enabled
  //add javascript click
  //on any click turn pop up an alert you need to register
}




