<?php

/**
 * @file
 * Module for playing around with javascript
 * 
 * Used for understanding how javascript is added to drupal when a module is
 * enabled and wants javascript functionality on the frontent.
 */



// create javascript that renders on every page.
// You could do this by adding it into your .info file in a file[] command
// Or you can do it here with drupal_add_js() function. 


/**
 * Implements hook_init();
 */
function addjavascript_init() {
  drupal_add_js(drupal_get_path('module','addjavascript').'/addjavascript.js');
}

