<?php

/**
 * @file
 * Using this module to learn about drupal's menu system
 */

/**
 * Implements hook_menu();
 */
function menufun_menu() {
  $items['menufun'] = array(
    'title' => 'Greeting',
    'page callback' => 'menufun_hello',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,   
  );
  $items['menufunargs'] = array(
    'title' => 'Greeting with arguments',
    'page callback' => 'menufun_helloargs',
    'page arguments' => array('amy', 'newcomb'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,   
  );
  
  return $items;
}

/**
 * Page callback.
 */
function menufun_hello() {
  return t('Hello!');
}

/**
 * page callback when there are arguments
 */
function menufun_helloargs($first='',$last='',$first2='',$last2='') {
  return t('Hello @first @last! I know you have the hots for @first2 @last2', array('@first'=>$first, '@last'=>$last,'@first2'=>$first2, '@last2'=>$last2));
}