<?php

/**
 * @file
 * Using this module to learn about drupal's menu system
 */

/**
 * Implements hook_menu();
 */
function menufun_menu() {
  $items['menufun'] = array(
    'title' => 'Greeting',
    'page callback' => 'menufun_hell0',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,   
  );
  
  return $items;
}

/**
 * Page callback.
 */
function menufun_hello() {
  return t('Hello!');
}