<?php

/**
 * @file
 * Using this module to learn about drupal's menu system
 */

/**
 * Implements hook_menu();
 */
function menufun_menu() {
  $items['menufun/menufun'] = array(
    'title' => 'Greeting',
    'page callback' => 'menufun_hello',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM, 
    'access callback' => 'user_access',
    'access arguments' => array('post comments'),
  );
  $items['menufunnav/menufunargs'] = array(
    'title' => 'Greeting with arguments',
    'page callback' => 'menufun_helloargs',
    'page arguments' => array('amy', 'newcomb'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,   
    'file' => 'menufun.inc',
  );
  $items['menufunnav'] = array(
    'title' => 'Greetings from the menu link',
    'page callback' => 'menufunnav_hello',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'weight'=> -1,
    'file' => 'menufun.inc'
  );
  $items['tabs'] =array(
    'title' => 'Tabs Overview',
    'page callback' => 'tabs_overview',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
   $items['tabs/first'] = array(
    'title' => 'First Tab',
    'access callback' => TRUE,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
 $items['tabs/second'] = array(
    'title' => 'Second Tab',
    'page callback' => 'tab_second',
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
  );  
      
  
  return $items;
}

/**
 * Page callback.
 */
function menufun_hello() {
  return t('Hello!');
}

function tabs_overview() {
  return t('Tabs are stupendous');
}

function tab_second() {
  return t('Welcome to the second tab');
}